-- Create a simple 'users' table to act as your "spreadsheet"
create table public.users (
  id bigint generated by default as identity primary key,
  usuario text not null,
  email text not null,
  password text not null, -- Storing plain text as requested for "simple" auth (or simple hash if preferred later)
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Disable RLS for simplicity (or enable and allow public read if needed)
-- Since this is a custom auth, we need public access to read/check credentials
alter table public.users enable row level security;

create policy "Enable read access for all users"
on public.users for select
using (true);

-- Insert a test user
insert into public.users (usuario, email, password)
values ('Admin', 'admin@videosia.com', '123456');
