const fs = require('fs');

// The base64 image data from the webhook response
const base64Image = '/9j/4AAQSkZJRgABAQAAAQABAAD/7QB8UGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAGAcAigAWkZCTUQyMzAwMDkxZDAyMDAwMDEyMjIwMDAwODIyNTAwMDA0MjI5MDAwMGRjNGEwMDAwZDc2MzAwMDA0NDdkMDAwMGY1OWQwMDAwYTBhZjAwMDA4M2NiMDAwMAD/2wCEAAUGBgsICwsLCwsNCwsLDQ4ODQ0ODg8NDg4ODQ8QEBARERAQEBAPExITDxARExQUExETFhYWExYVFRYZFhkWFhIBBQUFCgcKCAkJCAsICggLCgoJCQoKDAkKCQoJDA0LCgsLCgsNDAsLCAsLDAwMDQ0MDA0KCwoNDA0NDBMUExMTnP/CABEIAyACgAMBIgACEQEDEQH/xADwAAABBQEBAQEAAAAAAAAAAAADAQIEBQYHAAgJAQEBAQEBAQEAAAAAAAAAAAAAAQIDBAUGEAABAgUDAgMGBQMFAAAAAAABAAIDEBEgMBIhMQRBE0BRBSIyYXGBFEJSkbFQYoIzcqHR8BEAAQMBBQQHBgQGAgIDAQAAAQACEQMEEBIhMSBBUWETIjBxgZHwBTJAobHBQlJy0RQjM2Lh8VCCFUMkYJLCEgEAAgICAwEBAQEBAAAAAAABABEQISAxMEFRYXGBkSDRAAECAwYGAwEBAQAAAAAAAAEAESExQRBRYXGBkSBAobHB8DDR4fFQYP/aAAwDAQACEAMRAAA=...';

// Remove data URL prefix if present
const base64Data = base64Image.replace(/^data:image\/\w+;base64,/, '');

// Convert to buffer
const imageBuffer = Buffer.from(base64Data, 'base64');

// Write to file
fs.writeFileSync('generated_image.jpg', imageBuffer);

console.log('Image successfully saved to generated_image.jpg');
console.log('File size:', imageBuffer.length, 'bytes');
